---
title: "Peer Review Doc"
author: "Devanshi Pandya, Chinmay Amin, Archie JU"
date: "4/14/2021"
output:
  pdf_document: default
  html_document: default
---
<<<<<<< HEAD
## Note to Reader
The group we were assigned to review did not submit a project draft and only had their proposal uploaded. As a result, we will evaluate each of the three datasets and research questions they recommended in their project proposal. The only categories we could evaluate them on was "Introduction and Data" as well as "Final Considerations."
=======
### Note to Reader
The group we were assigned to review did not submit a project draft and only had their proposal uploaded. As a result, we will evaluate each of the three data sets and research questions they recommended in their project proposal. Therefore, the only categories we could evaluate them on was "Introduction and Data" as well as "Final Considerations."
>>>>>>> cae3f9c02d2625b4b10fa196e65c8e838a272892

## Peer Feedback 

### Introduction and Data


Dataset 1: 

a) The authors clearly state their research question for this dataset. They should also include a null and alternate hypothesis rather than simply including their prediction.

b) Since this is only a proposal, the authors are missing their motivation/ background to studying the topic

c) The proposal did include references to the dataset, but did not properly cite with MLA or APA 

d) The authors did indicate that their data was collected through webscraping the "Encyclopedia Titanica" website, but did not indicate when the data was collected

e) The group does not specify if they manipulated any variables and did not address missing data

f) The authors state relevant variables, but don't describe them in detail. 


Dataset 2: 

a) Two research questions are provided, along with a null and alternate hypothesis. When writing their project draft, the team should decide which they want to study.  

b) Authors have done a good job in describing the background information about their dataset and why their study will be important.

c) Source of data is included in a link, and should be cited using the proper format if necessary.

d) The authors do not include how and when the data was collected and would be a good idea if they mention that in their project draft.

e) Since the group has not yet completed the methodology section of their report, they have not yet manipulated the chosen dataset.

f) The cases and relevant variables should be described in an in-depth manner so that the readers of the report can understand their calculations, visualizations, and conclusions better.

<<<<<<< HEAD

Dataset 3: 

a) The authors list two research questions. In their final project report, they should narrow this down to one research question that they want to explore in depth. Moreover, the authors only list their predictions for the results of the data analysis. In their project report they should include a null and alternate hypothesis.

b) The group clearly indicates the motivation behind choosing the dataset in question. This looks good for the final project report

c) The authors state the source of the dataset and provide a reference. They might want to consider using a formal citation for their source in the final copy, perhaps through MLA or APA

d) While the group does state how the data was collected (through webscraping), they do not indicate when it was collected. It might be a good idea for the group to clarify this, should they choose this dataset for their final project.

e) The group does not indicate if they manipulated any variables, since this is only a proposal. The group also does not describe if any data is missing.

f) The authors mention what some of the variables describe, but do not do so in depth. In the final report they should be clearer about what measurement is reflected by a particular variable name. 

#### Final Considerations

Yo archie just answer these questions for the proposal in general, not each dataset individually. 

What is one question you have for the group after reading their analysis?
What is one thing the group has done especially well?



=======
Dataset 3:
a) Two research questions are provided, along with null and alternative hypothesis. When writing their project draft, the team should decide which they want to study. 
b) Authors have done a good job in describing the background information about their dataset -- the need to statistically predict players' success in NBA -- and why their study will be important for the basketball industry.
c) Source of data is included in a link, and should be cited using the proper format (APA or MLA) if necessary.
d) The authors do not include how and when the data was collected and would be a good idea if they mention that in their project draft.
e) Since the group has not yet completed the methodology section of their report, they have not yet manipulated the chosen dataset.
f) The case is well explained and the two research variable -- point per game & position of player -- are self-explanatory to audiences. If necessary, the author may want to explain the five different position in basketball a bit: what are they and how are they different.

#### Final Considerations
What is one question you have for the group after reading their analysis?
What is one thing the group has done especially well?

Dataset 1:
a) Isn't this dataset the same as Lecture Notes #21 Logistic Regression? You should avoid using dataset covered in the class as part of the final project requirement.
b) The author does a good job selecting proper variable -- passenger class -- that may be have actual cause-and-effect relationship with the response variabel -- passenger survival rate. 

Dataset 2:
a) How do you want to study the relationship between two dummy explanatory variable and one dummy response variable? What visualization technique do you want to employ?
b) They've chosen an especially relevant topic -- police killing. The could yield interesting results if anlayzed well.

Dataset 3:
a) How do you measure success in NBA? Which variable in the dataset represent it?
b) The two research questions are easy to be analyzed and the explanatory variables makes sense in real world -- points-per-game and positions can be important for basketball player's success.
>>>>>>> cae3f9c02d2625b4b10fa196e65c8e838a272892
